version: "3.5"

services:
  db:
    image: mariadb:10.5
    container_name: db
    command:
      - "mysqld"
      - "--character-set-server=utf8mb4"
      - "--collation-server=utf8mb4_unicode_ci"
    volumes:
      - "./db:/var/lib/mysql"
    environment:
      - MYSQL_ALLOW_EMPTY_PASSWORD=yes
      - MYSQL_DATABASE=flarum
      - MYSQL_USER=flarum
      - MYSQL_PASSWORD=IcAxxAvQ-4FEY-w8OxDBHJ
      - MYSQL_ROOT_PASSWORD= IcAxxAvQ-4FEY-w8OxDBHJ
    restart: always

  msmtpd:
    image: crazymax/msmtpd:latest
    container_name: flarum_msmtpd
    environment:
      - SMTP_HOST=172.17.0.1
      - SMTP_PORT=25
      - SMTP_FROM=devcom-u23253.vm.elestio.app@vm.elestio.app
    restart: always

  flarum:
    image: crazymax/flarum:${SOFTWARE_VERSION_TAG}
    restart: always
    container_name: flarum
    ports:
      - "172.17.0.1:8000:8000"
    depends_on:
      - db
      - msmtpd
    entrypoint: /data/docker-entrypoint.sh
    volumes:
      - "./data:/data"
      - "./docker-entrypoint.sh:/data/docker-entrypoint.sh"
    environment:
      - PUID=1000
      - PGID=1000
      - DB_HOST=db
      - DB_NAME=flarum
      - DB_USER=flarum
      - DB_PASSWORD=IcAxxAvQ-4FEY-w8OxDBHJ
      - MEMORY_LIMIT=256M
      - UPLOAD_MAX_SIZE=16M
      - OPCACHE_MEM_SIZE=128
      - REAL_IP_FROM=0.0.0.0/32
      - REAL_IP_HEADER=X-Forwarded-For
      - LOG_IP_VAR=remote_addr
      - FLARUM_DEBUG=false
      - FLARUM_BASE_URL=https://devcom-u23253.vm.elestio.app

